version: '3'

services:
  meili:
    container_name: meilisearch
    image: getmeili/meilisearch
    environment:
      - MEILI_ENV=development
    ports:
      - 7700:7700
    volumes:
      - mellistore:/data.ms

volumes:
  pgstore:
  mellistore:
