version: '3'

services:
  meilisearch:
    image: getmeili/meilisearch
    restart: on-failure
    environment:
      - MEILI_ENV=development
      - MEILI_NO_ANALYTICS=true
    ports:
      - 7700:7700
    networks:
      - back-tier
    volumes:
      - mellistore:/data.ms

#  mailhog:
#    image: mailhog/mailhog:latest
#    restart: always
#    networks:
#      - back-tier
#    ports:
#      - 1025:1025
#      - 8025:8025

volumes:
  pgstore:
  mellistore:

networks:
  back-tier:
